### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by ghost** [recurser/pivotal-to-trello#2]
When I'm using the tool I get an error after setting up all the targets for my stories.

```
Beginning import...
/home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!': 400 Bad Request (RestClient::BadRequest)
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-tracker-0.5.12/lib/pivotal-tracker/story.rb:8:in `all'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-tracker-0.5.12/lib/pivotal-tracker/proxy.rb:60:in `load_found'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-tracker-0.5.12/lib/pivotal-tracker/proxy.rb:48:in `proxy_found'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-tracker-0.5.12/lib/pivotal-tracker/proxy.rb:15:in `all'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/pivotal_wrapper.rb:22:in `stories'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/core.rb:19:in `import!'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/runner.rb:100:in `import'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/runner.rb:18:in `execute!'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/runner.rb:12:in `execute'
  from /home/phill/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pivotal-to-trello-0.1.2/bin/pivotal-to-trello:10:in `<top (required)>'
  from /home/phill/.rbenv/versions/2.1.1/bin/pivotal-to-trello:23:in `load'
  from /home/phill/.rbenv/versions/2.1.1/bin/pivotal-to-trello:23:in `<main>'
```

**Comment by vmueller71** [comment]
The patch works like a charm!
Thanks :)

**Comment by recurser** [comment]
Thanks for the report @Phill, and apologies for the delay. I've just pushed [version 0.2.0](https://rubygems.org/gems/pivotal-to-trello/versions/0.2.0) which should fix this.
