### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by garnold** [recurser/pivotal-to-trello#7]
Hello, 

I'm receiving the following error when attempting to install the Gem:

```
$ gem install pivotal-to-trello  --user-install --no-rdoc --no-ri
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: pivotal-tracker requires rest-client (~> 1.6.0), rest-client (~> 1.6.0); ruby-trello requires rest-client (~> 1.7.2)
$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [arm-linux-eabihf]
$ gem -v
1.8.23
```

Any help would be greatly appreciated.

Geoff.

**Comment by garnold** [comment]
Quick follow-up: I was able to resolve the issue by first installing the 2 versions of `rest-client`, then installing `pivotal-to-trello`:

```
$ gem install rest-client --user-install --no-rdoc --no-ri --version 1.6.0
Fetching: mime-types-2.4.3.gem (100%)
Fetching: rest-client-1.6.0.gem (100%)
Successfully installed mime-types-2.4.3
Successfully installed rest-client-1.6.0
2 gems installed

$ gem install rest-client --user-install --no-rdoc --no-ri --version 1.7.2
Fetching: netrc-0.10.2.gem (100%)
Fetching: rest-client-1.7.2.gem (100%)
Successfully installed netrc-0.10.2
Successfully installed rest-client-1.7.2
2 gems installed

$ gem install pivotal-to-trello --user-install --no-rdoc --no-ri
Building native extensions.  This could take a while...
Fetching: happymapper-0.4.1.gem (100%)
Fetching: pivotal-tracker-0.5.12.gem (100%)
Fetching: pivotal-to-trello-0.1.2.gem (100%)
Successfully installed libxml-ruby-2.8.0
Successfully installed happymapper-0.4.1
Successfully installed pivotal-tracker-0.5.12
Successfully installed pivotal-to-trello-0.1.2
4 gems installed
```

**Comment by garnold** [comment]
Spoke too soon... I'm getting the following error when running `pivotal-to-trello`:

```
$ pivotal-to-trello -h
/usr/lib/ruby/1.9.1/rubygems/specification.rb:1637:in `raise_if_conflicts': Unable to activate pivotal-tracker-0.5.12, because rest-client-1.7.2 conflicts with rest-client (~> 1.6.0), rest-client (~> 1.6.0) (Gem::LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:746:in `activate'
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:780:in `block in activate_dependencies'
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:766:in `each'
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:766:in `activate_dependencies'
    from /usr/lib/ruby/1.9.1/rubygems/specification.rb:750:in `activate'
    from /usr/lib/ruby/1.9.1/rubygems.rb:1232:in `gem'
    from /home/pi/.gem/ruby/1.9.1/bin/pivotal-to-trello:22:in `<main>'
```

**Comment by garnold** [comment]
Anyone?

**Comment by kirs** [comment]
Don't install it via rubugems: just clone https://github.com/recurser/pivotal-to-trello/pull/3 fork, `bundle` it and run locally.

**Comment by recurser** [comment]
Thanks for the report @garnold, and apologies for the delay. I've just pushed [version 0.2.0](https://rubygems.org/gems/pivotal-to-trello/versions/0.2.0) which should fix this.
