### ISSUE TITLE
Error if any label chosen

### ISSUE THREAD

**Issue by zevaverbach** [recurser/pivotal-to-trello#9]
```
/Library/Ruby/Gems/2.0.0/gems/ruby-trello-1.3.0/lib/trello/card.rb:321:in `add_label': undefined method `valid?' for "red":String (NoMethodError)
from /Library/Ruby/Gems/2.0.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/trello_wrapper.rb:77:in `add_label'
from /Library/Ruby/Gems/2.0.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/core.rb:58:in `block in import!'
from /Library/Ruby/Gems/2.0.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/core.rb:19:in `each'
from /Library/Ruby/Gems/2.0.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/core.rb:19:in `import!'
from /Library/Ruby/Gems/2.0.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/runner.rb:100:in `import'
from /Library/Ruby/Gems/2.0.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/runner.rb:18:in `execute!'
from /Library/Ruby/Gems/2.0.0/gems/pivotal-to-trello-0.1.2/lib/pivotal_to_trello/runner.rb:12:in `execute'
from /Library/Ruby/Gems/2.0.0/gems/pivotal-to-trello-0.1.2/bin/pivotal-to-trello:10:in `<top (required)>'
from /usr/bin/pivotal-to-trello:23:in `load'
from /usr/bin/pivotal-to-trello:23:in `<main>'
```

**Comment by InteNs** [comment]
got the same

**Comment by kamilbednarz** [comment]
+1

**Comment by gareth-lloyd** [comment]
+1

**Comment by recurser** [comment]
Thanks for the report @zevaverbach, and apologies for the delay. I've just pushed [version 0.2.0](https://rubygems.org/gems/pivotal-to-trello/versions/0.2.0) which should fix this.
